### ISSUE TITLE
Зачем придумали велосипед второй раз? )

### ISSUE THREAD

**Issue by brend8c** [mamoru-kun/vscode-fish-text#4]
Это риторический вопрос нежели технический..
Можно же ввести loremru и он генерирует тест на русском языке.. 
**Пример:**
_Далеко-далеко за, словесными горами в стране гласных и согласных живут рыбные тексты. То свой семантика составитель всеми одна пор, ведущими встретил вопрос страну! Семантика заманивший они инициал. Курсивных ее до последний не._
Или то-же самое на английском языке Lorem
**Пример:**
_Lorem ipsum dolor sit amet consectetur adipisicing elit. Sequi dicta nostrum officiis culpa. Aspernatur ratione cumque, deleniti ipsam praesentium cupiditate voluptas eaque illum minus, vel provident. Assumenda facere libero nesciunt?_

**Comment by AlexAtHome** [comment]
@brendan8c, хотелось генератор именно грамотно построенного текста прямо в IDE. `loremru` отдаёт набор слов, который лишь отдалённо напоминает нормальную русскую речь. Так что использование этого плагина - дело вкуса.
