### ISSUE TITLE
Рыбный текст для других типов файлов

### ISSUE THREAD

**Issue by CodeLit** [mamoru-kun/vscode-fish-text#5]
Как включить рыбный текст для других типов файлов? У меня только работает в файлах без расширения и в html файлах. 
Мне нужно как-то включить его в файлах Laravel - .blade.php, и также для .py файлов.
Заранее благодарю.

**Comment by AlexAtHome** [comment]
@CodeLit PHP, по идее, должен работать. Я проверю на выходных, в чем проблема.

Python добавлю.

**Comment by CodeLit** [comment]
@mamoruuu Спасибо. Я также обнаружил, что он не работает в компонентах тега `<template>`  фреймворка .vue 
Как вариант я бы сделал поле "типы файлов" в настройках vscode, чтобы пользователь сам мог выбрать, где плагин будет работать.
Но я понятия не имею, как разрабатывать расширения :/

**Comment by AlexAtHome** [comment]
@CodeLit, сделал по вашему совету, сделав настойки для плагина. Уже релизнул в версии 1.1.0. Если будут какие-то вопросы, то пишите в этом же issue
